import type { TweetDraft, QueueStats, WeekStats, TodaySummary } from './types';

export const MOCK_TWEETS: TweetDraft[] = [
  {
    id: 'tw-001',
    voice: 'founder',
    pillar: 'security',
    sourceType: 'trending-topic',
    sourceRef: { label: '@zacodil thread on CVE-2026-25253', url: 'https://x.com/zacodil/status/example' },
    body: 'Spent the morning reading CVE reports so you don\'t have to. Short version: if your OpenClaw is on port 18789 with no auth, you\'re already owned.',
    charCount: 152,
    status: 'queued',
    gateScore: 8.2,
    gateScores: { voice: 9, accuracy: 7, engagement: 8, guidelines: 9 },
    gateFlags: [{ type: 'accuracy-note', detail: 'CVE number referenced — verify against source', severity: 'warning' }],
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tw-002',
    voice: 'brand',
    pillar: 'ease',
    sourceType: 'blog-promotion',
    sourceRef: { label: 'DIY vs Hosted blog post', url: '/blog/diy-vs-hosted' },
    body: 'Running your own AI infrastructure sounds cool until your Saturday becomes "why is everything on fire." Clawer manages the stack. You manage the strategy.',
    charCount: 160,
    status: 'queued',
    gateScore: 7.8,
    gateScores: { voice: 8, accuracy: 9, engagement: 7, guidelines: 8 },
    gateFlags: [],
    createdAt: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tw-003',
    voice: 'founder',
    pillar: 'ai-teams',
    sourceType: 'build-in-public',
    body: 'Hot take: 90% of "AI wrappers" are just fancy prompt engineering. The 10% that matter run 5 agents in parallel, pick the best output, and feed the results into the next agent. That\'s what we built.',
    charCount: 198,
    status: 'approved',
    gateScore: 9.1,
    gateScores: { voice: 9, accuracy: 9, engagement: 10, guidelines: 9 },
    gateFlags: [],
    createdAt: new Date(Date.now() - 6 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tw-004',
    voice: 'brand',
    pillar: 'use-cases',
    sourceType: 'community-engagement',
    body: 'Asked 50 solopreneurs what kills their mornings. Answer: email triage, status updates, content drafts. Our users automate all three before 9am. The rest of the morning is actual work.',
    charCount: 183,
    status: 'queued',
    gateScore: 7.4,
    gateScores: { voice: 8, accuracy: 7, engagement: 7, guidelines: 8 },
    gateFlags: [{ type: 'accuracy-note', detail: 'Verify "50 solopreneurs" stat has backing', severity: 'warning' }],
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tw-005',
    voice: 'founder',
    pillar: 'security',
    sourceType: 'competitor-reaction',
    body: 'Every week another "AI agent platform" launches with a slick homepage and no mention of auth, isolation, or audit logs. Security is boring until it isn\'t.',
    charCount: 158,
    status: 'scheduled',
    gateScore: 8.6,
    gateScores: { voice: 9, accuracy: 8, engagement: 8, guidelines: 9 },
    gateFlags: [],
    scheduledAt: new Date(Date.now() + 3 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tw-006',
    voice: 'brand',
    pillar: 'education',
    sourceType: 'content-pillar',
    body: 'Thread: How multi-agent AI systems actually work (without the hype). Most explanations skip the hard parts — orchestration, error handling, cost control. Here\'s the real picture. 🧵',
    charCount: 179,
    status: 'queued',
    gateScore: 8.0,
    gateScores: { voice: 8, accuracy: 8, engagement: 8, guidelines: 8 },
    gateFlags: [],
    createdAt: new Date(Date.now() - 14 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'tw-007',
    voice: 'founder',
    pillar: 'use-cases',
    sourceType: 'build-in-public',
    body: 'We published 11 blog posts in one week using AI agents. Not "AI helped me write" — AI drafted, reviewed, scored, and queued. I approved or killed. 2 hours of my time total.',
    charCount: 177,
    status: 'queued',
    gateScore: 8.9,
    gateScores: { voice: 9, accuracy: 9, engagement: 9, guidelines: 9 },
    gateFlags: [],
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_QUEUE_STATS: QueueStats = {
  totalDrafts: 14,
  approved: 3,
  scheduledToday: 2,
  pillarBalance: {
    security: 40,
    ease: 25,
    'ai-teams': 15,
    'use-cases': 15,
    education: 5,
  },
};

export const MOCK_WEEK_STATS: WeekStats = {
  contentPublished: 8,
  engagementRate: 3.2,
  signups: 89,
  topPerformer: { text: '"42K instances exposed..."', engagement: 4.8 },
  pillarBalance: {
    security: 40,
    ease: 25,
    'ai-teams': 15,
    'use-cases': 15,
    education: 5,
  },
  insight: 'Security content outperforms by 2x. Consider a "Security Week" campaign.',
};

export const MOCK_TODAY_SUMMARY: TodaySummary = {
  draftsAwaitingReview: 3,
  scheduledToday: 2,
  scheduledItems: ['9am tweet', 'noon blog'],
  yesterdayReach: 8200,
  yesterdayEngagement: 3.1,
  activeCampaign: { name: 'ClawHub Security', day: 3, totalDays: 5 },
};
