/**
 * SOUL.md and Agent File Generation
 * 
 * Generates personalized agent workspace files based on configuration.
 */

export interface AgentSOULConfig {
  name: string;
  emoji: string;
  role: string;
  personality: string;
  skills?: string[];
  canDelegateTo?: string[];
  canReceiveFrom?: string[];
}

export function generateCustomAgentSOUL(config: AgentSOULConfig): string {
  const delegationSection = config.canDelegateTo?.length
    ? `\n## Delegation\nYou can delegate tasks to: ${config.canDelegateTo.join(', ')}\nUse \`sessions_spawn\` to delegate work.\n`
    : '';

  const receiveSection = config.canReceiveFrom?.length
    ? `\n## Receiving Tasks\nYou may receive delegated tasks from: ${config.canReceiveFrom.join(', ')}\nComplete them and report back via \`sessions_send\`.\n`
    : '';

  return `# SOUL.md — ${config.name} ${config.emoji}

## Who I Am
I'm **${config.name}**, ${config.role}.

## Personality
${config.personality}

## My Role
${config.role}
${delegationSection}${receiveSection}
## Guidelines
- Stay focused on my specialty
- Be helpful, direct, and efficient
- If a task is outside my expertise, say so
- Keep responses concise unless detail is needed

## Platform Features
Read PLATFORM.md for documentation on Clawer.ai features:
- Creating tasks for the kanban board
- Setting up cron jobs for scheduled tasks
- Saving files to appear in the dashboard
- Managing memory and daily notes
- Agent communication and delegation

---
*Generated by Clawer.ai*
`;
}

export function generateCustomAgentAGENTS(config: AgentSOULConfig): string {
  return `# AGENTS.md — ${config.name} Workspace

## About
This workspace belongs to **${config.name}** ${config.emoji}, a custom agent.

## Role
${config.role}

## Available Skills
${config.skills?.map(s => `- ${s}`).join('\n') || '- No specific skills configured'}

## Session Management
- Read SOUL.md on every session start
- Keep workspace organized
- Update memory files with important context
`;
}

export function generateInitialDailyNote(agentName: string): string {
  const today = new Date().toISOString().split('T')[0];
  return `# ${today} — ${agentName}

## Created
Agent provisioned today.

## Notes
- First session
`;
}

export function generateUserMdTemplate(userName: string): string {
  return `# USER.md — About My Human

- **Name:** ${userName}

## Communication Style
- Direct and efficient
- Prefers results over process
`;
}
