export default function BrandBiblePage() {
  return (
    <div className="flex flex-col items-center justify-center py-24 text-center">
      <p className="text-5xl mb-4">📖</p>
      <h2 className="text-xl font-semibold text-gray-700">Brand Bible — Coming in Phase 1</h2>
      <p className="text-sm text-gray-400 mt-2 max-w-sm">
        Your brand voice guide, positioning, messaging framework, and battlecards — all in one place.
        Generated by the Brand Foundation Builder.
      </p>
    </div>
  );
}
